"""empty message

Revision ID: 55c9af8e5226
Revises: c2ecac2829df
Create Date: 2025-04-06 18:15:39.748806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c9af8e5226'
down_revision: Union[str, None] = 'c2ecac2829df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('region', sa.String(), nullable=True))
    op.drop_column('locations', 'area')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('locations', 'region')
    # ### end Alembic commands ###
