"""empty message

Revision ID: bc129c5328be
Revises: 0558264d7c2f
Create Date: 2025-04-06 20:42:56.106650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc129c5328be'
down_revision: Union[str, None] = '0558264d7c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
