"""empty message

Revision ID: f47642a6ef1b
Revises: 55c9af8e5226
Create Date: 2025-04-06 20:24:21.365238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47642a6ef1b'
down_revision: Union[str, None] = '55c9af8e5226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('locations_latitude_key', 'locations', type_='unique')
    op.drop_constraint('locations_longitude_key', 'locations', type_='unique')
    op.drop_constraint('locations_name_key', 'locations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('locations_name_key', 'locations', ['name'])
    op.create_unique_constraint('locations_longitude_key', 'locations', ['longitude'])
    op.create_unique_constraint('locations_latitude_key', 'locations', ['latitude'])
    # ### end Alembic commands ###
